language: ruby

addons:
  postgresql: '9.4'
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

rvm:
  - 2.6.3

cache: bundler

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
